[2025-01-26T19:04:01.665+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T19:04:01.674+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T19:04:01.677+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [queued]>
[2025-01-26T19:04:01.678+0000] {taskinstance.py:2866} INFO - Starting attempt 10 of 10
[2025-01-26T19:04:01.683+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> on 2025-01-25 00:00:00+00:00
[2025-01-26T19:04:01.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=264) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T19:04:01.689+0000] {standard_task_runner.py:72} INFO - Started process 265 to run task
[2025-01-26T19:04:01.689+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'simulative_example_basic_dag', 'read_data_from_faker_api_and_load_to_pg.load_data_to_pg', 'scheduled__2025-01-25T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/simulative_example_basic_dag.py', '--cfg-path', '/tmp/tmptr320p4w']
[2025-01-26T19:04:01.691+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask read_data_from_faker_api_and_load_to_pg.load_data_to_pg
[2025-01-26T19:04:01.935+0000] {task_command.py:467} INFO - Running <TaskInstance: simulative_example_basic_dag.read_data_from_faker_api_and_load_to_pg.load_data_to_pg scheduled__2025-01-25T00:00:00+00:00 [running]> on host b82bd748d7ce
[2025-01-26T19:04:01.973+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulative_example_basic_dag' AIRFLOW_CTX_TASK_ID='read_data_from_faker_api_and_load_to_pg.load_data_to_pg' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T00:00:00+00:00'
[2025-01-26T19:04:01.974+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T19:04:01.974+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T19:04:01.974+0000] {logging_mixin.py:190} INFO - Current task name:read_data_from_faker_api_and_load_to_pg.load_data_to_pg state:running start_date:2025-01-26 19:04:01.674387+00:00
[2025-01-26T19:04:01.974+0000] {logging_mixin.py:190} INFO - Dag name:simulative_example_basic_dag and current dag run status:running
[2025-01-26T19:04:01.975+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T19:04:01.980+0000] {logging_mixin.py:190} INFO - {'name': 'Тарас Демидович Гаврилов', 'age': 80, 'address': 'к. Нерчинск, пер. Мичурина, д. 51 стр. 818, 373183', 'email': 'mitofanlitkin@example.net', 'phone_number': '+7 724 571 83 33', 'registration_date': '2024-09-23T12:48:16.044327', 'created_at': '2024-10-09T07:04:23.623318', 'updated_at': '2024-09-28T18:59:38.118622', 'deleted_at': None}
[2025-01-26T19:04:01.981+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 47, in load_data_to_pg
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2025-01-26T19:04:01.987+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-26T19:04:01.987+0000] {logging_mixin.py:190} INFO - Task start:2025-01-26 19:04:01.674387+00:00 end:2025-01-26 19:04:01.987028+00:00 duration:0.312641
[2025-01-26T19:04:01.987+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): read_data_from_faker_api_and_load_to_pg.load_data_to_pg> dag:<DAG: simulative_example_basic_dag> dagrun:<DagRun simulative_example_basic_dag @ 2025-01-25 00:00:00+00:00: scheduled__2025-01-25T00:00:00+00:00, state:running, queued_at: 2025-01-26 19:03:59.442464+00:00. externally triggered: False>
[2025-01-26T19:04:01.987+0000] {logging_mixin.py:190} INFO - Failure caused by the JSON object must be str, bytes or bytearray, not dict
[2025-01-26T19:04:01.988+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=simulative_example_basic_dag, task_id=read_data_from_faker_api_and_load_to_pg.load_data_to_pg, run_id=scheduled__2025-01-25T00:00:00+00:00, execution_date=20250125T000000, start_date=20250126T190401, end_date=20250126T190401
[2025-01-26T19:04:01.994+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T19:04:01.994+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task read_data_from_faker_api_and_load_to_pg.load_data_to_pg (the JSON object must be str, bytes or bytearray, not dict; 265)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simulative_example_basic_dag.py", line 47, in load_data_to_pg
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
[2025-01-26T19:04:02.043+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-26T19:04:02.176+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T19:04:02.178+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
